FROM ubuntu:22.04
ENV CONDA_PREFIX="/root/miniconda3"
ENV PATH="/root/miniconda3/bin:/root/miniconda3/envs/mlpack/bin:${PATH}"
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Kolkata
ENV LD_LIBRARY_PATH=/usr/local/lib

RUN apt-get update && apt-get upgrade

